version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:12.12
    restart: always
    environment:
      - POSTGRES_USER=initdemyUser
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=initdemy
    ports:
      - 5432:5432
    volumes:
      - db_vol:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    depends_on:
      - postgres
      - adminer
    ports:
      - 5000:5000

volumes:
  db_vol: {}
